language: python
python:
  - "2.7"
install: pip install --upgrade -r requirements.txt
script: python setup.py tests --type=unit --coverage
before_install:
  - pip install codecov
after_success:
  - cd python && codecov
