language: python
python:
  - "2.6"
  - "2.7"
#  - "3.4"
#  - "3.5"
install: pip install -r requirements.txt
script: python setup.py tests --type=unit --coverage
before_install:
  - pip install codecov
after_success:
  - cd python && codecov
