#!/bin/bash
set -e
# wget --quiet -O dirac_ui.tgz  https://cernbox.cern.ch/index.php/s/MDFe8MvVL9Y1GpQ/download
# tar xvzf dirac_ui.tgz
# rm dirac_ui.tgz
# echo -e "[DIRAC]\nDiracEnvSource = ${HOME}/dirac_ui/bashrc" > ${HOME}/.gangarc
# echo -e "[Configuration]\nRUNTIME_PATH=GangaDirac" >> ${HOME}/.gangarc
# echo -e "[defaults_DiracProxy]\ngroup=gridpp_user" >> ${HOME}/.gangarc
ganga -g

wget --quiet -O udocker.tmp https://raw.githubusercontent.com/indigo-dc/udocker/master/udocker.py
sed -e "s/split('-')/split('+')/" udocker.tmp > udocker
rm udocker.tmp
chmod u+rx ./udocker
./udocker install

mkdir bin
wget --quiet -O bin/singularity https://cernbox.cern.ch/index.php/s/eGrWrDOz09PJ4T0/download
