/PhysicsList/OmitMuonicProcesses true
/PhysicsList/OmitHadronicProcesses true

/rat/db/set DETECTOR geo_file "geo/snoplus_water.geo"

/run/initialize
##########EVENT LOOP############
/rat/proc frontend
/rat/proc trigger
/rat/proc eventbuilder
/rat/proc calibratePMT

/rat/proc waterFitter

/rat/proc outntuple
/rat/proclast outroot
##########EVENT LOOP############
# Solar B8 neutrinos needed
/generator/add solar b8:nue
/generator/solar/direction 0.0 0.0 -1.0
/generator/rate/set 1

/rat/run/start
exit
