dir_image_data = [
"32 32 10 1",
". c None",
"# c #000000",
"b c #00c000",
"e c #303030",
"h c #400000",
"d c #585858",
"g c #a0a0a4",
"f c #c0c0c0",
"a c #c0ffc0",
"c c #ffffff",
"...###..........................",
"...#aa##........................",
".###baaa##......................",
".#cd##baaa##....................",
".#cccd##baaa##..##e.............",
".#cccccd##baaa##aaa##...........",
".#cccccccd##baaaaaaaa##.........",
".#cccccccccd##baaaaaaa#.........",
".#cccccfcffgg#bbbbaaaaa#........",
".#ccccccfcfffd#bbbbbbaa#........",
".#cccfcfcfcffgd##bh#bbba#.......",
".#ccccfcfffffffgd#dd##ba#.......",
".#cfcfcfcfffffffffgfgd#bb#......",
".#ccfcfffffffffgfgfgfgd#b#......",
".#cfcfcfffffffffgfgfggd#b#......",
".#fcfffffffffgfgfgggggd#b#......",
".#cfcfffffffffgfgfggggd#b#......",
".#fffffffffgfgfgggggggdhb#......",
".#ffffffffffgfgfggggggd#b#......",
".#ggfffffgfgfgggggggggd#b#......",
".#ddggffffgfgfggggggggd#b#......",
"..##ddggfgfgggggggggggd#b#......",
"....##ddgggfggggggggggd#b#......",
"......##ddggggggggggggd#b#......",
"........##ddggggggggggd#b#......",
"..........##ddggggggggd#b#......",
"............##ddggggggd#b###....",
"..............##ddggggd#b#####..",
"................##ddggd#b######.",
"..................##ddd#b#####..",
"....................##d#b###....",
"......................####......"
]
file_image_data = [
"32 32 61 1",
"b c #000000",
"c c #010101",
"f c #020202",
"2 c #040404",
"X c #060606",
"d c #070707",
"W c #0a0a0a",
"y c #0b0b0b",
"P c #0c0c0c",
"6 c #0d0d0d",
"e c #0e0e0e",
"Z c #121212",
"T c #131313",
"5 c #171717",
"i c #1c1c1c",
"U c #bcbcbc",
"V c #c1c1c1",
"M c #c5c5c5",
"N c #c9c9c9",
"4 c #cccccc",
"F c #cdcdcd",
"G c #d0d0d0",
"L c #d4d4d4",
"j c #d5d5d5",
"O c #d8d8d8",
"D c #d9d9d9",
"w c #dadada",
"p c #dbdbdb",
"z c #dddddd",
"C c #dedede",
"J c #e1e1e1",
"1 c #e2e2e2",
"x c #e3e3e3",
"Q c #e4e4e4",
"R c #e5e5e5",
"Y c #e6e6e6",
"l c #e7e7e7",
"q c #e8e8e8",
"3 c #e9e9e9",
"o c #eaeaea",
"H c #ebebeb",
"S c #ececec",
"m c #ededed",
"I c #eeeeee",
"K c #efefef",
"k c #f0f0f0",
"u c #f1f1f1",
"B c #f2f2f2",
"r c #f3f3f3",
"t c #f4f4f4",
"h c #f5f5f5",
"v c #f6f6f6",
"0 c #f7f7f7",
"A c #f8f8f8",
"s c #f9f9f9",
"a c #fafafa",
"g c #fbfbfb",
"n c #fcfcfc",
"E c #fdfdfd",
"# c #fefefe",
". c #ffffff",
".#abccbbbbbbbbbbbdbefb.gg.hg#...",
"...ijkklmmmmmmmmno.pabb..a..hqk.",
"rstbgtuvuuuuuuuuj.wrxyzb.Am....B",
"...baCxBoooooooohDuEhbFGy..rBH.v",
"srtbmBhIBBBBBBBB.JsaKbLMNbI.s.O.",
".ngPQhhRSSSSSSSSlIHpoTUpVjW..n.E",
"n..XQYSIIIIIIIIItoSEkbybZbbb.t0.",
"E..bEuItSSSSSSSSkC.JnzgK1.QcE#.k",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
"E..bEuItSSSSSSSSSSSSSSSSmJ0b.Ag.",
"n..XQYSIIIIIIIIIIIIIIIIIHK0cA.gv",
".ngPQhhRSSSSSSSSSSSSSSSSmSQbB...",
"srtbmBhIBBBBBBBBBBBBBBBBBQJ2.KA.",
"...baCxBooooooooooooooool3ty.s..",
"rstbgtuvuuuuuuuuuuuuuuuuu.Hbkq.S",
"...ijkklmmmmmmmmmmmmmmmmov45....",
".#abccbbbbbbbbbbbbbbbbbbb6ebg.H."
]

cern_logo_image_data = [
"100 100 47 1",
"i c #00294f",
". c #002e53",
"k c #06345a",
"z c #0e3c61",
"d c #103b5f",
"r c #113e62",
"j c #1b476a",
"l c #224c6e",
"h c #234f72",
"B c #2c5576",
"C c #355c7c",
"M c #39607f",
"m c #3c6382",
"L c #466a88",
"# c #4d718d",
"S c #4f7390",
"P c #50738f",
"A c #587a94",
"q c #5f809b",
"Q c #607f97",
"H c #69869d",
"n c #6c8ba3",
"R c #6f90a9",
"F c #718ea5",
"b c #7995ab",
"a c #7e9ab0",
"c c #819aaf",
"y c #839db2",
"I c #8ba3b7",
"e c #94aabb",
"w c #98afc0",
"v c #9ab1c2",
"p c #a7bac9",
"O c #a8bfd1",
"N c #aec1cf",
"u c #afc1d0",
"E c #b1c2ce",
"K c #b8c8d5",
"x c #c1ced9",
"J c #c6d3dd",
"o c #cbd8e1",
"t c #d4dee6",
"G c #dde5eb",
"s c #e2e9ee",
"D c #e6ecf1",
"g c #edf2f5",
"f c #fefefe",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"...#abbbababbbaaaabbbbbabbbbbabbbbbbcbabbabbabbbbbbbaabbabbbbbbbbbbbbabbbbbbaabbbabbbbbabbbbbbad....",
"...efffffffffffffffffffgfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffh....",
"...efii...i.ii.i..iiiii..i...i..i.i.ii.i....i...ii...i..i...ii.i...ii.i..i...i..i.i.ii.i...i.jfh....",
"...efi....................................................................k..................lfj....",
"...efi.......................................................................................jfh....",
"...efi.......................................................................................lfl....",
"...ef........................................................................................lfj....",
"...efi......k...k............................................................................jfh....",
"...ef................................kjhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlhhhhhhhhhhhhmfh....",
"...efi.....k.............k......jnogfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffl....",
"...efi..k....................jpffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffj....",
"...efi.........k...........qgffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffj....",
"...ef................k...#fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffh....",
"...efi.................rsfffffffffffgtuvwwpxgffffffffffffgwvvvvvevvvvvvvvwwveevvvvvvvvvvvvvvvpfj....",
"...efi................afffffffffgyh...........zAoffffffffftk.................................jfj....",
"...efi...............tffffffffer..................AgffffffffB.....k..........................jfh....",
"...ef..............zgfffffffb.......................CDfffffffA...............................jfl....",
"...efi............rfffffffE..............k......i.kjl.AfffffffFi.............................jfj....",
"...efi...........zfffffffm...................CeGfffffglktffffffH.............................jfl....",
"...efi..........kffffffDk.................AGfffffffffffeiIffffff#......................gGeB..jfj....",
"...ef...........Dfffffo................rEfffffffffffffffs.Affffffh.....................fffA..jfj....",
"...ef..........pfffffJ...........z...dKffffffffoyLhrrkzjMF.Lffffff.pC.................lfffj..jfh....",
"...efi........mffffft..............iyffffffgbj..............HfffffxifJk...............Afff...jfl....",
"...efi........fffffg..............rgfffffxl...........k......efffffL#ffA..............Nffg...jfj....",
"...ef........wfffffj.............Afffffxz............k........DfffffisffE............isffJ...rfl....",
"..kefi......zfffffb.............vffffgBi......................dfffffbBfffs............fffy...jfj....",
"...efi......Offffg.............Effffp........................k.cfffff.sfffgk.........kfffm...jfj....",
"...efi.....kfffffC.......k...iKffffP............................fffffHjfffffk........Cfffd...jfh....",
"...efi.....affffG............pffffB........k...k................Affffgi.gfffg........bfff....jfj....",
"...efi.....gffffm...........Hffffj...............k...............fffffj..gfffo.......offD....jfh....",
"...ef.k...jfffffi..........lffffh..........................k.....effffe...gfffb......gffu....jfl....",
"...efi....yffffe....z.....igfffP.................................rfffff...kffffj.....fffH....jfj....",
"...ef.....Dffffj..........BIEte..................................igffffk...Cfffg....rfffh....jfl....",
"...ef.....fffff...................................................vffffP....pfffn...#fff.....jfj....",
"...efi...rfffft......i........ii...i.....i.i......................mffffE.....gfff...wfff.....jfj....",
"...ef....Lffffy.....ygffffKB.jfgffffffk.tfgfgDwk....ffti....gp....dffffgi....Lfffa..Gfft.....jfh....",
"...ef....affffL...rffnrkdPsfijfyCCCCCC..tfCCCyffz...fOfQ...ifO.....fffff......Dfff..fffe.....jfj....",
"...efi...pffffj...ffk......m.jfAi......itf....Bfe...fnKf....fO....ifffffr.....mfffP.fffL.....jfj....",
"...efi...Jffffz..#fA.........jfQ........tf....rfw...fnkfJ..ifO.....DffffQ.....igffGlfffj.....jfl....",
"...ef....offffd..pfk.........jfstttttt..tfi...ufj...fn.PfL..fE.....GffffK......bfffFfff......jfj....",
"...ef....offffz..ofk.........jfObbbFbc..GfoJoffC....fn.itf..fE.....Gffffgi.....zffffffg......jfj....",
"...efi...xffffk..pfk.......k.jfH........tfFaEfH.....fn..dfp.fN.....sfffffk....k.gfffffx.k....jfh....",
"...efi...uffffr..mfb.........jfQ........Gfi.ipfF....fn...bflfO.....ffffffj......wfffffb......jfl....",
"...ef....yffffm...gfhi....ib.jfA........tf....pfb...fn....ggfu.....ffffffn......mfffffB......jfj....",
"...ef....#ffffb...kgfKLmLefgijfKIIIyII..tfi...iefa..fn....jffu....kffffffx......kfffffk......jfl....",
"...ef....lffffJ.....AogffoHk.rtttttttGk.OG......Itn.tA.....yte....Bfffffff.......fffff.......jfj....",
"...efi...kfffff.........i...........ii..i.........................Ifffffff.......ffffGi......jfj....",
"...efi....Dffffz.....................k............................Dfffffffl......gfffp.......jfh....",
"...ef.....vffffR.....BuoG....................k.k.................kffffffffF......GfffA.......jfj....",
"...efi....Cffffg.....Lfff....................k...................Fffffffffx......Gfffj.......jfj....",
"...efi.....fffffj....Lfff.......................z................gfffffffffi.....sfff........jfl....",
"...efi.....DffffJ....Bfffk......................................Cfffffgffff......gffg........jfl....",
"...efi.....vfffffj...rfffj......................................DffffyEffffB.....fffo........jfl....",
"...efi.....mfffffti...fffm...........k........k................Sfffff.Pffffb.....fffI........jfj....",
"...ef.......ffffffL..ifffI.........................k......k....fffffe.jffffoi...jfffm........jfl....",
"...ef.......gffffffk..Gfft...................................ixfffffk.ifffff....nfff....k....jfl....",
"...efi......vffffffG..Ifff....k....................k.........QfffffH...Dffffk...Jffg.........jfj....",
"...ef.......mfffffffpiBfffB.................................Bfffffs....pffffC..ifffv.........jgl....",
"...ef........ffffffffI.Gffp................................jffffffk....#ffffy..CfffB.........jgj....",
"...ef....k...gffffffffIiJff.......k.........k......k......BffffffL.....rfffft..offf..........jgj....",
"...ef........pfffffffffEibfP.............................LffffffI.......fffff.kfffp..........jsl....",
"...efi.......mffffffffffgdjG...................k........effffffpi.......sffffkwfffj......k...rfl....",
"...efi.......kffffffffffffHik.........................lgffffffp.........vffffmIffG...........rfl....",
"...ef.........gffffmfffffffgCi......................kEfffffffJ..........LffffemffB.......k...jfj....",
"...ef.........pffffAjgfffffffDL...................jKfffffffft...........zffffGkft............jfj....",
"...efi........LffffK..offfffffffNC............ijcgfffffffffs.............fffffifj............jfj....",
"...efi.....k..kfffff...PfffffffffffgxyQLmLAROsffffffffffffD..............Gffffkn.............jfl....",
"...ef..........gffffz....pfffffffffffffffffffffffffffffffg.......k.......effffL..........k...jfj....",
"...ef.....k...kOffff#.....dpffffffffffffffffffffffffffffgk...............Lffffv..............jfh....",
"...ef........k.LffffK........Hgfffffffffffffffffffffffffk...............BkffffD............k.jfl....",
"...ef..........kffffgi.........kAJffffffffffffftfffffffk...............Ffifffff..............jfl....",
"...efi..........gffffk.....k..BGnji.jCAHynALjkivffffffz...............Off.offffz.............jfj....",
"...efi..........ufffDB.........hfffgon........effffffj..............jgfffByffff#.............jfh....",
"...efi..........meB.............zgffffsj.....Iffffffj..............wfffffBCffffp.............jfl....",
"...efi..k.........................Jfffffoj..bffffffl.............bfffffgr.kffffDi............jfj....",
"...efi.............................AffffffznffffffC..........ilpffffffe...ifffff.............jfj....",
"...efi......................z........KfffrAffffffm........zLOfffffffGj.....offffr............jfh....",
"...efi.......................k........ror#ffffffLdGoKOoGDfffffffffsm.......bffffA............jfl....",
"...ef...........k.......................LffffffAkgffffffffffffffKli........BffffO............jfl....",
"...efi.....k...........................BffffffnkgffffffffffffKm.............ffffg............jfj....",
"...efi...................k...k........Bffffffb.jHvKtDDGJpRBk................gffff............jfh....",
"...ef.....................k..........lffffffy..................k............xffffj...........jfj....",
"...efi..............................jffffffI................................nffffn...........jfj....",
"...ef..............................rffffffp......k..........................lffffK...........jfl....",
"...ef.................k...........zffffffNi..................................ffffg...........jfh....",
"...efi...k.......................kffffffK.................................k..gffff...........jfl....",
"...efi.....................k...k.gfffffJi..........k.........................Kffffh..........jfl....",
"...efi..........................gfffffti.....................................Hffffn..........jfj....",
"...ef...................k......sfffffG................z............k.........jffffK..........jfh....",
"...efi................k.......GfffffD..........................i..............fffff..........jfj....",
"...efdzjrzrrzrzzrrrrrrrrzrzzztffffffrzdzzzzzkdzzzdzzzzzzddzzddddzdzzzzzzkdzzzkgffffrzzzdzzzzzBfl....",
"...effffffffffffffffffffffffffffffffffffffffffffffffffffffffgfggfffffffffffffffffffffffffffffffl....",
"...jBBBBBCBBBBBBBBBBCBBBBBBBBBBBBBCBBBBCBBBBBBBBCBBBBBBBBBBBBBBBBBBBBBBBBBBBBCBBBCBBBBBBBBBBCBBk....",
"....................................................................................................",
"....k...........k....................................................k..............................",
"....................................................................................................",
"..k................................................................................................."
]
lhcb_logo_image_data = [
"100 68 24 1",
"a c #444388",
"e c #4d4d8e",
"l c #565894",
"h c #5f629a",
"# c #696da1",
"t c #6e396d",
"i c #7278a7",
"o c #7b82ad",
"r c #83345f",
"d c #858db4",
"f c #8e98ba",
"n c #97a2c0",
"m c #a1adc7",
"k c #aab7cd",
"g c #b3c2d3",
"j c #bdcdda",
"s c #c32537",
"b c #c6d7e0",
"q c #ce2330",
"c c #cfe2e6",
". c #d9eded",
"u c #dcc5c5",
"v c #eb3636",
"p c #ee1c1c",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"..........................................................................#aaaaaab..................",
"............................................................................aaaaa...................",
".............................................................................aaaa...................",
".............................................................................aaac...................",
"............................................................................daaa....................",
"............................................................................aaaa....................",
"............................................................................aaaa....................",
"............................................................................aaa.....................",
"...........................................................................aaaa.....................",
"...........................................................eaaaaf...a......aaaa......g..............",
".........aaaaaaaaag........faaaaaaaaaf.aaaaaaaaaa.......aaaae...haaaa......aaa....aaaaaaa...........",
"...........aaaaa..............aaaaa......caaaaa.......#aaaa.......aaa.....iaaa..iaaaaaaaaa..........",
"...........aaaaj..............aaaa........aaaa.......aaaaa........aa......aaaa.aa.....eaaaa.........",
"...........aaaa..............haaaa.......aaaaa......aaaaa.........ka......aaajaa.......aaaa.........",
"..........aaaaa..............aaaaa.......aaaaa.....aaaaa...........a.....aaaaga........aaaa.........",
"..........aaaal..............aaaaj.......aaaa.....baaaa#...........g.....aaaaa.........aaaa.........",
"..........aaaa..............baaaa.......maaaa.....aaaaa..................aaaa..........aaaa.........",
".........aaaaa..............aaaaa.......aaaaa.....aaaaa.................maaaa..........aaaa.........",
".........aaaal..............aaaaaaaaaaaaaaaal....daaaak.................aaaa..........laaa..........",
".........aaaa..............naaaa.......iaaaa.....aaaaa..................aaaa..........aaaa..........",
"........aaaaa..............aaaaa.......aaaaa.....aaaaa.................iaaa..........aaaa...........",
"........aaaaa..............aaaah.......aaaan.....aaaaa.................aaaa..........aaaa...........",
"........aaaa...............aaaa.......baaaa......aaaaa.................aaaa.........aaae............",
".......oaaaa..........a...aaaaa.......aaaaa......oaaaa.................aaac........aaaa.............",
".......aaaaa.........aa...aaaaa.......aaaaa.......aaaaf.........aa....aaaa........aaak..............",
".......aaaa.........aa...baaaa........aaaa.........aaaa.......fae.....aaaa.......aaa................",
"......aaaaa.......aaaa...aaaaa.......aaaaa..........aaaaa...oaaf......aaaa.....aaag.................",
"....aaaaaaaaaaaaaaaaaa.aaaaaaaaa..#aaaaaaaaag.........aaaaaaa...........baaaaaae....................",
"aaaa..................a.........aag.........#aaaaaaaaal.....daaaaaaaaaaaao....gaaaaaaaaaapppppaaaaaa",
"aaaaaa.....aaaaaac....aaa.....aaaaaaa.....aaaaaaaaaa......g....aaaaaaae...jaaad...aaaaapppppaaaaaaaa",
"aaaaaaa....aaaaaaaab..aaam....aaaaaaaa....aaaaaaaaa....gaaaaaa..aaaaaa....aaaaaak..naqppppaaaaaaaaaa",
"aaaaaaa....baaaaaaaaa..aaa....caaaaaaa....maaaaaaa.....aaaaaaaaa.jaaaa....aaaaaaaa...pppaaaaaaaaaaaa",
"aaaaaaa.....aaaaaaaaaa.aaa.....aaaaaaa.....aaaaaal....aaaaaaaaaaaiaaaal...aaaaaaarp...kaaaaaaaaaaaaa",
"aaaaaaaa....aaaaaaaaaaiaaah....aaaaaaan....aaaaaa.....aaaaaaaaaaaaaaaaa....aaaaapppp...eaaaaaaaaaaaa",
"aaaaaaaa.....aaaaaaaaaaaaaa....oaaaaaaa....eaaaaa.....aaaaaaaaaaaaaaaaa....aaappppsaa...haaaaaaaaaaa",
"aaaaaaaa.....aaaaaaaaaaaaaa.....aaaaaaa.....aaaaa.....aaaaaaaaaaaaaaaaa....apppppaaaa....aaaaaaaaaaa",
"aaaaaaaal....aaaaaaaaaaaaaab....aaaaaaa.....aaaaa.....aaaaaaaaaaaaaaaaaa....pppaaaaaaa....aaaaaaaaaa",
"aaaaaaaaa....daaaaaaaaaaaaaa................oaaaac....aaaaaaaaaaaaaaaaaa....paaaaaaaaa....aaaaaaaaaa",
"aaaaaaaaa.....aaaaaaaaaaaaaa.....aaaaaaa.....aaaaa.....aaaaaaaaaaaaaaatpu...oaaaaaaaaaa....aaaaaaaaa",
"aaaaaaaaaa....aaaaaaaaaaaaaan....aaaaaaaj....aaaaa.....aaaaaaaaaaaaatpppp....aaaaaaaaaa....aaaaaaaaa",
"aaaaaaaaaa....daaaaaaaaaaaaaa....aaaaaaaa....aaaaag....eaaaaaaaaaaappppsa.....aaaaaaaaa....aaaaaaaaa",
"aaaaaaaaaa.....aaaaaaaaaaaaaa.....aaaaaaa.....aaaaa.....aaaaaaaaapp.psaaa.....maaaaaaaa....aaaaaaaaa",
"aaaaaaaaaao....aaaaaaaaaaaaaa.....aaaaaaa.....aaaaaa.....aaaaaapppv.aaaaaa...a.caaaaaaa....aaaaaaaaa",
"aaaaaaaaaaa....aaaaaaaaaaaaaaa....aaaaaaal....aaaaaaa....oaaappppp..aaaaaa....a.jaaaaae....aaaaaaaaa",
"aaaaaaaaaaa.....aaaaaaaaaaaaaa.....aaaaaaa.....aaaaaaa.....pppppaa..jaaaaa....aa..cae.....aaaaaaaaaa",
"aaaaaaaaa.........#aaaaaaaaf.........fa..........aaaaaag....ppaaa....aaaaaa...aaaf.......caaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaatpp.......gaa.aaaaaa...kaaaaa...oaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaapppppaaaaaaaaaaaaaaaa....aaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaapppaaaaaaaaaaaaaaaaaa#...aaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...baaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa....aaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac...aaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...aaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa....aaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa....aaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.......aaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadmaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
]