#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

if [ -z "$1" ]
then
    echo "No version number specified"
    exit
fi

VERSION=$1
STAGING_DIR=$HOME/ganga_release_staging/
INSTALL_DIR=/afs/cern.ch/sw/ganga/install/
GIT_URL=git@github.com:ganga-devs/ganga.git

#Get the directory where this script is stored
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
THIS_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

echo "-------------"
echo "Updating repo"
echo "-------------"
cd $STAGING_DIR/$VERSION
git pull

echo "--------------"
echo "Installing pre"
echo "--------------"
git archive --prefix=$VERSION-pre/ --format=tar HEAD | gzip >Ganga-$VERSION-pre.tar.gz
cp Ganga-$VERSION-pre.tar.gz $INSTALL_DIR/tarball/
tar xf $INSTALL_DIR/tarball/Ganga-$VERSION-pre.tar.gz --directory $INSTALL_DIR
echo "Copied tarball to $INSTALL_DIR/tarball/Ganga-$VERSION-pre.tar.gz"
echo "Installed pre to $INSTALL_DIR"

echo "--------------------"
echo "Installing externals"
echo "--------------------"
$THIS_DIR/ganga-install-externals $VERSION-pre

echo "-------------------------------"
echo "Creating release notes template"
echo "-------------------------------"
cat << EOF > release/ReleaseNotes-$VERSION
**************************************************************************************************************
$VERSION (`date "+%Y/%m/%d"`)


--------------------------------------------------------------------------------------------------------------
ganga/python/Ganga
--------------------------------------------------------------------------------------------------------------
* ...

**************************************************************************************************************
EOF

git add release/ReleaseNotes-$VERSION
git commit -m"Adding release notes template"

echo "----------------------"
echo "Pushing release branch"
echo "----------------------"
git flow release publish $VERSION
git push
