#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

if [ -z "$1" ]
then
    echo "No version number specified"
    exit
fi

VERSION=$1
STAGING_DIR=$HOME/ganga_release_staging/
INSTALL_DIR=/afs/cern.ch/sw/ganga/install/

echo "-------------"
echo "Fetching repo"
echo "-------------"
cd $STAGING_DIR
git clone git@github.com:ganga-devs/ganga-git-testing.git $VERSION-pre
cd $VERSION-pre
git flow init -d
git config gitflow.prefix.versiontag v
git flow release start $VERSION

echo "--------------"
echo "Installing pre"
echo "--------------"
git archive --prefix=$VERSION-pre/ --format=tar HEAD | gzip >Ganga-$VERSION-pre.tar.gz
cp Ganga-$VERSION-pre.tar.gz $INSTALL_DIR/tarball/
tar xf $INSTALL_DIR/tarball/Ganga-$VERSION-pre.tar.gz --directory $INSTALL_DIR

echo "--------------------"
echo "Installing externals"
echo "--------------------"
$INSTALL_DIR/$VERSION-pre/release/tools/ganga-install-externals $VERSION-pre

echo "----------------------"
echo "Pushing release branch"
echo "----------------------"
git flow release publish $VERSION
git push
