#!/usr/bin/python
import os
import sys

outroot = "/home/karl/images"

try:
  infileName = sys.argv[ 1 ]
except IndexError:
  infileName = ""

if not os.path.exists( infileName ):
  infileName = ""

infile = open( infileName )

directory = infile.readline().strip()

inputLine = "true"

while inputLine:
  inputLine = infile.readline().strip()
  if inputLine:
    relpath = inputLine.split()[ 1 ]
    inpath = os.path.join( directory, relpath )
    outpath = os.path.join( outroot, inpath.strip( "/" ) )
    outdir = os.path.dirname( outpath )
    print outdir, outpath
    os.system( "mkdir -p %s" % outdir )
    os.system( "cp %s %s" % ( inpath, outpath ) )

infile.close()
