#! /usr/bin/env bash

# This file will set things up so that the tests can be run over the release branch from GitHub

set -euo pipefail
IFS=$'\n\t'

if [ -z "$1" ]
then
    echo "No version number specified"
    exit
fi

VERSION=$1
INSTALL_DIR=/afs/cern.ch/sw/ganga/install

echo "Removing old pre (if it exists)"
rm -rf ${INSTALL_DIR}/${VERSION}-pre1
if [ -d "${INSTALL_DIR}/${VERSION}-pre" ]; then
    mv ${INSTALL_DIR}/${VERSION}-pre ${INSTALL_DIR}/${VERSION}-pre1
fi
rm -f ${INSTALL_DIR}/tarball/Ganga-${VERSION}-pre.tar.gz

echo "Creating new pre install folder"
mkdir -p ${INSTALL_DIR}/${VERSION}-pre/reports/latest/output

echo "Downloading release branch"
wget https://github.com/ganga-devs/ganga/archive/release/${VERSION}.tar.gz --output-document=/tmp/${VERSION}.tar.gz --quiet #Download tar file to /tmp

echo "Extracting release branch to pre directory"
tar xzf /tmp/${VERSION}.tar.gz --strip-components=1 --directory=${INSTALL_DIR}/${VERSION}-pre #extract it, stripping the leading directory

echo "Tarring-up pre folder"
cd ${INSTALL_DIR}
tar zcf ${INSTALL_DIR}/tarball/Ganga-${VERSION}-pre.tar.gz ${VERSION}-pre 

VERSION_SPACES="`echo "${VERSION}" | sed "s/\./ /g"`" # "6.1.2" → "6 1 2"

echo 
echo 
echo "Login to gangage@lxplus and run : sh ~/test/test_ganga_generic.sh ${VERSION_SPACES}"
echo "Login to gangalb@lxplus and run : sh ~/test/test_ganga_lhcb.sh ${VERSION_SPACES}"
echo "Login to gangaat@lxplus and run : sh ~/test/test_ganga_atlas.sh ${VERSION_SPACES}"

echo "Once tests have completed, run:"
echo   "${INSTALL_DIR}/${VERSION}-pre/bin/ganga --test -o'[TestingFramework]ReleaseTesting=True' -o'EnableHTMLReporter=True' -o'EnableTestRunner=False'"

