#! /usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

if [ $# -eq 0]
then
    echo "Please provide a version string e.g. 6.1.2"
fi

if [ -z "$1" ]
then
    echo "No version number specified e.g. 6.1.2"
    exit
fi

VERSION=$1
INSTALL_DIR=/afs/cern.ch/sw/ganga/install

echo "------------------"
echo "Installing release"
echo "------------------"

mkdir ${INSTALL_DIR}/${VERSION}
wget https://github.com/ganga-devs/ganga/archive/${VERSION}.tar.gz --output-document=/tmp/${VERSION}.tar.gz --quiet #Download tar file to /tmp
tar xzf /tmp/${VERSION}.tar.gz --strip-components=1 --directory=${INSTALL_DIR}/${VERSION} #extract it, stripping the leading directory
cd ${INSTALL_DIR}
tar zcf tarball/Ganga-${VERSION}.tar.gz ${VERSION} #Tar it up again with the new leading directory
echo "Copied tarball to ${INSTALL_DIR}/tarball/Ganga-${VERSION}.tar.gz"
echo "Installed release to ${INSTALL_DIR}"


echo "--------------------"
echo "Installing externals"
echo "--------------------"

$INSTALL_DIR/$VERSION/release/tools/ganga-install-externals $VERSION


echo "-----------------"
echo "Generating manual"
echo "-----------------"

echo login to gangalb@lxplus and run this command:
echo sh \~/test/generate_lhcb_manual.sh `echo "${VERSION}" | sed "s/\./ /g"`


echo "--------------------"
echo "Copying test reports"
echo "--------------------"

cp -r ${INSTALL_DIR}/${VERSION}-pre/reports ${INSTALL_DIR}/${VERSION}/.

