#!/bin/bash
source /cvmfs/lhcb.cern.ch/lib/LbEnv
export GANGA_CONFIG_PATH=GangaLHCb/LHCb.ini
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/cvmfs/sft.cern.ch/lcg/releases/LCG_97python3/Python/3.7.6/x86_64-centos7-gcc9-opt/lib
/cvmfs/sft.cern.ch/lcg/releases/LCG_97python3/Python/3.7.6/x86_64-centos7-gcc9-opt/bin/python3 -m venv venv
. venv/bin/activate
pip install --upgrade pip setuptools pytest
pip install -e ganga[LHCb]
(cd ganga && pip install --upgrade -r requirements.txt)
lhcb-proxy-init
/root/venv/bin/pytest --testLHCb /root/ganga/ganga/GangaLHCb/test --cov-report term --cov-report xml:cov-GangaLHCb.xml --cov /root/ganga/ganga/GangaLHCb --junitxml tests-GangaLHCb.xml
