#!/bin/bash
source /cvmfs/lhcb.cern.ch/lib/LbEnv && source LbLogin.sh
export GANGA_CONFIG_PATH=GangaLHCb/LHCb.ini
virtualenv -p python3 venv
rm -f venv/bin/python
. venv/bin/activate
pip install --upgrade pip setuptools pytest
pip install -e ganga[LHCb]
(cd ganga && pip install --upgrade -r requirements.txt)
lhcb-proxy-init
/root/venv/bin/pytest --testLHCb /root/ganga/ganga/GangaLHCb/test --cov-report term --cov-report xml:cov-GangaLHCb.xml --cov /root/ganga/ganga/GangaLHCb --junitxml tests-GangaLHCb.xml
