name: CI Push Testing

on: [pull_request]

jobs:

  singularity-test:
    name: Singularity Controller Tests
    runs-on: ubuntu-18.04
    steps:


    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
          build-essential \
          libssl-dev \
          uuid-dev \
          libgpgme11-dev \
          squashfs-tools \
          libseccomp-dev \
          pkg-config
    - name: Install Singularity
      env:
        SINGULARITY_VERSION: 3.2.1
      run: |
        export GOPATH=/tmp/go
        mkdir -p $GOPATH
        sudo mkdir -p /usr/local/var/singularity/mnt && \
        mkdir -p $GOPATH/src/github.com/sylabs && \
        cd $GOPATH/src/github.com/sylabs && \
        wget -qO- https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-${SINGULARITY_VERSION}.tar.gz | \
        tar xzv && \
        cd singularity && \
        ./mconfig -p /usr/local && \
        make -C builddir && \
        sudo make -C builddir install          
          
    - name: Check out code for the container build
      uses: actions/checkout@v1

    - name: Build Container
      run: singularity pull docker://mongo:latest

    - name: UDocker Installation
      run: |
        curl https://raw.githubusercontent.com/indigo-dc/udocker/master/udocker.py > udocker
        chmod u+rx ./udocker
        ./udocker install
    - name: UDocker Link
      run: sudo ln -s ./udocker /bin
    - name: Test uDocker installation
      run: ./udocker pull mongo:latest

    - name: Set up Python 3
      run: |
        sudo apt-get install -y python3
        sudo apt-get install -y python3-pip
    - name: Install dependencies
      run: |
        pip3 install --upgrade pip setuptools wheel
        pip3 install -e .[dev]
        pip3 install pymongo pytest spython
      
    - name: Test Container Controllers
      run: python3 -m pytest ganga/GangaCore/test/GPI/db_testing/TestContainer.py
      env:
        GANGA_GITHUB_HOST: True
        MONGODB_HOST: mongodb
        MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }}

